import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

// CC9EFE

export default function Home() {
  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <Head>
        <title>Test SEO</title>
        <meta name="description" content="description" />
        <meta
          property="og:image"
          content="https://res.cloudinary.com/dycjbf6ub/image/upload/v1656059261/daily/daily_1_rg4oxe.jpg"
        />
        <meta property="og:url" content="http://localhost:3000/" />
        <meta property="og:description" content="description" />
        <meta property="og:title" content="title" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>

        <script>
          {(function () {
            var w = window;

            if (w.ChannelIO) {
              return (
                window.console.error ||
                window.console.log ||
                function () {}
              )("ChannelIO script included twice.");
            }

            var ch = function () {
              ch.c(arguments);
            };

            ch.q = [];
            ch.c = function (args) {
              ch.q.push(args);
            };

            w.ChannelIO = ch;

            function l() {
              if (w.ChannelIOInitialized) {
                return;
              }

              w.ChannelIOInitialized = true;
              var s = document.createElement("script");
              s.type = "text/javascript";
              s.async = true;
              s.src = "https://cdn.channel.io/plugin/ch-plugin-web.js";
              s.charset = "UTF-8";
              var x = document.getElementsByTagName("script")[0];
              x.parentNode.insertBefore(s, x);
            }

            if (document.readyState === "complete") {
              l();
            } else if (window.attachEvent) {
              window.attachEvent("onload", l);
            } else {
              window.addEventListener("DOMContentLoaded", l, false);
              window.addEventListener("load", l, false);
            }
          })()}
          {ChannelIO("boot", {
            pluginKey: "318cc6ca-5597-4f84-94ec-775a7ba55153",
          })}
        </script>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
